<a href="https://colab.research.google.com/github/shallynagfase9/Python-for-Data-Science/blob/main/Numpy_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Array Manipulation
arr = np.random.randint(1,10, (4,4))
arr

array([[7, 6, 9, 5],
       [2, 7, 8, 7],
       [9, 8, 6, 6],
       [7, 5, 5, 9]])

In [ ]:
arr.reshape(8,2) # Changing dimensions

array([[7, 6],
       [9, 5],
       [2, 7],
       [8, 7],
       [9, 8],
       [6, 6],
       [7, 5],
       [5, 9]])

In [ ]:
arr

array([[7, 6, 9, 5],
       [2, 7, 8, 7],
       [9, 8, 6, 6],
       [7, 5, 5, 9]])

In [ ]:
arr.T     # Transpose of array


array([[7, 2, 9, 7],
       [6, 7, 8, 5],
       [9, 8, 6, 5],
       [5, 7, 6, 9]])

In [ ]:
arr.flatten()  # It,s going t put all kind of data in a 1-dimensional array

array([7, 6, 9, 5, 2, 7, 8, 7, 9, 8, 6, 6, 7, 5, 5, 9])

In [ ]:
np.expand_dims(arr, axis=1) # we are able to get the expanded array using this method

array([[[7, 6, 9, 5]],

       [[2, 7, 8, 7]],

       [[9, 8, 6, 6]],

       [[7, 5, 5, 9]]])

In [ ]:
np.expand_dims(arr, axis=0)

array([[[7, 6, 9, 5],
        [2, 7, 8, 7],
        [9, 8, 6, 6],
        [7, 5, 5, 9]]])

In [ ]:
data = np.array([[1], [2], [3]])
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data) # squeeze function is used to remove dimension in an array

array([1, 2, 3])

In [ ]:
np.repeat(data, 2) # Whatever data we have after using the repeat function we got the result in repeated form

array([1, 1, 2, 2, 3, 3])

In [ ]:
np.repeat(data, 5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [ ]:
np.roll(data, 2) # roll function will rotate the data

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# Numpy - Binary Operators
arr1 =np.random.randint(1,10, (3,4))
arr2 =np.random.randint(1,10, (3,4))

In [ ]:
arr1

array([[9, 3, 6, 8],
       [5, 2, 9, 2],
       [2, 9, 6, 4]])

In [ ]:
arr2

array([[4, 6, 9, 4],
       [7, 2, 4, 7],
       [8, 8, 5, 3]])

In [ ]:
arr1+arr2

array([[13,  9, 15, 12],
       [12,  4, 13,  9],
       [10, 17, 11,  7]])

In [ ]:
arr1-arr2

array([[ 5, -3, -3,  4],
       [-2,  0,  5, -5],
       [-6,  1,  1,  1]])

In [ ]:
arr1**arr2


array([[    6561,      729, 10077696,     4096],
       [   78125,        4,     6561,      128],
       [     256, 43046721,     7776,       64]])

In [ ]:
arr1/arr2

array([[2.25      , 0.5       , 0.66666667, 2.        ],
       [0.71428571, 1.        , 2.25      , 0.28571429],
       [0.25      , 1.125     , 1.2       , 1.33333333]])

In [ ]:
arr1 * arr2

array([[36, 18, 54, 32],
       [35,  4, 36, 14],
       [16, 72, 30, 12]])

In [ ]:
~arr1

array([[-10,  -4,  -7,  -9],
       [ -6,  -3, -10,  -3],
       [ -3, -10,  -7,  -5]])

In [ ]:
arr1>arr2

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True,  True,  True]])

In [ ]:
# Numpy - String Operations (Functions)
arr = np.array(["shally", "harpreet"])
arr

array(['shally', 'harpreet'], dtype='<U8')

In [ ]:
np.char.upper(arr)

array(['SHALLY', 'HARPREET'], dtype='<U8')

In [ ]:
np.char.capitalize(arr)

array(['Shally', 'Harpreet'], dtype='<U8')

In [ ]:
np.char.lower(arr)

array(['shally', 'harpreet'], dtype='<U8')

In [ ]:
np.char.title(arr)

array(['Shally', 'Harpreet'], dtype='<U8')

In [38]:
# Numpy - Mathematical Functions
arr1

array([[9, 3, 6, 8],
       [5, 2, 9, 2],
       [2, 9, 6, 4]])

In [39]:
np.sin(arr1)

array([[ 0.41211849,  0.14112001, -0.2794155 ,  0.98935825],
       [-0.95892427,  0.90929743,  0.41211849,  0.90929743],
       [ 0.90929743,  0.41211849, -0.2794155 , -0.7568025 ]])

In [40]:
np.cos(arr2)

array([[-0.65364362,  0.96017029, -0.91113026, -0.65364362],
       [ 0.75390225, -0.41614684, -0.65364362,  0.75390225],
       [-0.14550003, -0.14550003,  0.28366219, -0.9899925 ]])

In [41]:
arr2

array([[4, 6, 9, 4],
       [7, 2, 4, 7],
       [8, 8, 5, 3]])

In [42]:
np.tan(arr1)

array([[-0.45231566, -0.14254654, -0.29100619, -6.79971146],
       [-3.38051501, -2.18503986, -0.45231566, -2.18503986],
       [-2.18503986, -0.45231566, -0.29100619,  1.15782128]])

In [43]:
np.exp(arr1)

array([[8.10308393e+03, 2.00855369e+01, 4.03428793e+02, 2.98095799e+03],
       [1.48413159e+02, 7.38905610e+00, 8.10308393e+03, 7.38905610e+00],
       [7.38905610e+00, 8.10308393e+03, 4.03428793e+02, 5.45981500e+01]])

In [44]:
np.log10(arr1)

array([[0.95424251, 0.47712125, 0.77815125, 0.90308999],
       [0.69897   , 0.30103   , 0.95424251, 0.30103   ],
       [0.30103   , 0.95424251, 0.77815125, 0.60205999]])

In [45]:
np.power(arr1, 2) # It will give power of every element in an array with power 2

array([[81,  9, 36, 64],
       [25,  4, 81,  4],
       [ 4, 81, 36, 16]])

In [46]:
np.power(arr1, 3)

array([[729,  27, 216, 512],
       [125,   8, 729,   8],
       [  8, 729, 216,  64]])

In [47]:
# numpy module has no attribute mode, for mode you need to import module statistics
np.mean(arr1)

5.416666666666667

In [48]:
np.median(arr1)

5.5

In [49]:
np.std(arr1)

2.7220804951768454

In [50]:
np.var(arr1)

7.4097222222222205

In [51]:
np.min(arr1)

2

In [52]:
np.max(arr1)

9

In [54]:
# Numpy - Arithmetic Operations
# There are two ways to perform arithmetic operations using numpy
arr1


array([[9, 3, 6, 8],
       [5, 2, 9, 2],
       [2, 9, 6, 4]])

In [55]:
arr2

array([[4, 6, 9, 4],
       [7, 2, 4, 7],
       [8, 8, 5, 3]])

In [56]:
arr1 - arr2

array([[ 5, -3, -3,  4],
       [-2,  0,  5, -5],
       [-6,  1,  1,  1]])

In [57]:
np.subtract(arr1, arr2)

array([[ 5, -3, -3,  4],
       [-2,  0,  5, -5],
       [-6,  1,  1,  1]])

In [58]:
np.add(arr1, arr2)

array([[13,  9, 15, 12],
       [12,  4, 13,  9],
       [10, 17, 11,  7]])

In [59]:
np.multiply(arr1, arr2)

array([[36, 18, 54, 32],
       [35,  4, 36, 14],
       [16, 72, 30, 12]])

In [61]:
np.mod(arr1, arr2)

array([[1, 3, 6, 0],
       [5, 0, 1, 2],
       [2, 1, 1, 1]])

In [63]:
np.sqrt(arr1)

array([[3.        , 1.73205081, 2.44948974, 2.82842712],
       [2.23606798, 1.41421356, 3.        , 1.41421356],
       [1.41421356, 3.        , 2.44948974, 2.        ]])

In [65]:
np.power(arr1, arr2)

array([[    6561,      729, 10077696,     4096],
       [   78125,        4,     6561,      128],
       [     256, 43046721,     7776,       64]])

In [66]:
# Numpy - Statistical functions
arr1

array([[9, 3, 6, 8],
       [5, 2, 9, 2],
       [2, 9, 6, 4]])

In [67]:
np.mean(arr1)

5.416666666666667

In [68]:
np.median(arr1)

5.5

In [69]:
np.std(arr1)

2.7220804951768454

In [70]:
np.var(arr1)

7.4097222222222205