<a href="https://colab.research.google.com/github/shallynagfase9/Python-for-Data-Science/blob/main/Numpy_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]
print(l)

[1, 2, 3, 4, 5, 6]


In [5]:
array = np.array(l)

In [6]:
type(array)

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [10]:
array1 = np.array([[1,2,3],[4,5,6]])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array1.ndim  # ndim function is going to tell you the dimension of an array

2

In [13]:
array.ndim

1

In [14]:
mat = np.matrix(l)
mat


matrix([[1, 2, 3, 4, 5, 6]])

In [15]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6]])

In [17]:
a = array
a

array([1, 2, 3, 4, 5, 6])

In [18]:
array[0] = 100
a

array([100,   2,   3,   4,   5,   6])

In [19]:
b = np.copy(array)
b

array([100,   2,   3,   4,   5,   6])

In [20]:
b[0] = 200
b

array([200,   2,   3,   4,   5,   6])

In [21]:
a

array([100,   2,   3,   4,   5,   6])

In [22]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [25]:
iterable = (i*i for i in range(5))

In [26]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [28]:
np.fromstring('34 56 23', sep = " ")

array([34., 56., 23.])

In [29]:
np.fromstring('34, 56, 23', sep = ",")

array([34., 56., 23.])

In [30]:
array
array.size

6

In [31]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
array1.size


6

In [33]:
array1.shape

(2, 3)

In [34]:
array.shape

(6,)

In [38]:
array.dtype

dtype('int64')

In [39]:
array1.dtype

dtype('int64')

In [40]:
list(range(5))

[0, 1, 2, 3, 4]

In [42]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
list(range(0.4,10))

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
list(np.arange(0.4,10,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004]

In [52]:
np.linspace(1,5, 20) # linspace funcion will divide the scale of 1 to 5 into 20 equal parts

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [53]:
np.logspace(1,5, 10, base = 2) # logspace will divide the data into parts based on logarithmic with base 2

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [54]:
np.zeros(5) # zeros is a function which is used to generate any dimesnsion with zeros

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [59]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
np.ones((3, 4, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [64]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [67]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [68]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [71]:
arr1 = np.eye(5)  # eye function will return a identity matrix that will return 1 in a diagonal
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
# Converting array in a dataframe
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [73]:
np.random.rand(2,3)  # rando function will generate a random data
# it will produce dataset with random mean and standard deviation

array([[0.43750776, 0.97762167, 0.2675565 ],
       [0.99355889, 0.35432437, 0.71242081]])

In [74]:
np.random.randn(2,3) # randn function will produce dataset with mean = 0 and standard deviation = 1


array([[ 0.85273619, -0.70944851, -0.47424883],
       [ 1.37641027, -1.49515363, -0.08418321]])

In [76]:
arr2 = np.random.randint(1,5, (3,4))
arr2

array([[2, 2, 2, 3],
       [3, 3, 1, 4],
       [1, 1, 4, 2]])

In [77]:
arr2.size

12

In [78]:
arr2.shape

(3, 4)

In [81]:
arr2.reshape(6,2) # it will reshape the dimension but data will be same

array([[2, 2],
       [2, 3],
       [3, 3],
       [1, 4],
       [1, 1],
       [4, 2]])

In [82]:
arr2.reshape(6,3) # data cannot be fit in the specified dimension

ValueError: cannot reshape array of size 12 into shape (6,3)

In [83]:
arr2.reshape(4,-1)

array([[2, 2, 2],
       [3, 3, 3],
       [1, 4, 1],
       [1, 4, 2]])

In [87]:
arr2.reshape(2,2,3)

array([[[2, 2, 2],
        [3, 3, 3]],

       [[1, 4, 1],
        [1, 4, 2]]])

In [91]:
arr1 = np.random.randint(1, 10, (5,6))
arr1

array([[8, 9, 3, 5, 1, 7],
       [7, 6, 8, 5, 8, 4],
       [5, 3, 8, 2, 5, 9],
       [1, 4, 7, 5, 5, 3],
       [2, 7, 4, 4, 4, 3]])

In [92]:
arr1 > 8

array([[False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [93]:
arr1[arr1 > 8]

array([9, 9])

In [94]:
arr1

array([[8, 9, 3, 5, 1, 7],
       [7, 6, 8, 5, 8, 4],
       [5, 3, 8, 2, 5, 9],
       [1, 4, 7, 5, 5, 3],
       [2, 7, 4, 4, 4, 3]])

In [96]:
arr1[0]

array([8, 9, 3, 5, 1, 7])

In [97]:
arr1[2:4, [2,3]]

array([[8, 2],
       [7, 5]])

In [98]:
arr1[0, [0,1]]

array([8, 9])

In [99]:
arr1 = np.random.randint(1,3, (3,3))
arr1

array([[2, 2, 1],
       [1, 1, 2],
       [1, 2, 2]])

In [100]:
arr2 = np.random.randint(1,3, (3,3))
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [101]:
arr1 + arr2 # Index wise performing addition operation

array([[3, 4, 2],
       [2, 3, 4],
       [2, 3, 4]])

In [103]:
arr1 - arr2    # Index wise performing subtraction operation

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  1,  0]])

In [104]:
arr1  *  arr2  # Here you will get index wise matrix multiplication answer

array([[2, 4, 1],
       [1, 2, 4],
       [1, 2, 4]])

In [105]:
arr1@arr2 # Here you will get exact matrix multiplication answer

array([[5, 9, 8],
       [4, 6, 7],
       [5, 8, 9]])

In [106]:
arr1/arr2

array([[2. , 1. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 2. , 1. ]])

In [107]:
arr1/0

<ipython-input-107-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [110]:
# Numpy - Broadcasting
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [112]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [113]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [114]:
b = np.array([3,4,5])
b

array([3, 4, 5])

In [119]:
arr + b # here you will not be able to broadcast array


ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [116]:
b = np.array([[3,4,5]])
b

array([[3, 4, 5]])

In [117]:
arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [120]:
b.T

array([[3],
       [4],
       [5]])

In [122]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [123]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.30103]])

In [124]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [125]:
np.min(arr1)

1

In [126]:
np.max(arr1)

2