<a href="https://colab.research.google.com/github/shallynagfase9/Python-for-Data-Science/blob/main/Numpy_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy - Search, sort and counting functions
import numpy as np
arr = np.array([4, 2, 6, 8, 10, 9, 77, 56])
arr

array([ 4,  2,  6,  8, 10,  9, 77, 56])

In [2]:
np.sort(arr) # sort() function will sort the array in ascending order

array([ 2,  4,  6,  8,  9, 10, 56, 77])

In [4]:
np.searchsorted(arr, 6)

2

In [5]:
np.searchsorted(arr, 5)

2

In [9]:
arr1 = np.array([0, 56,21,56,32,67,21,67,34,89])
arr1

array([ 0, 56, 21, 56, 32, 67, 21, 67, 34, 89])

In [10]:
np.count_nonzero(arr1) # It will give the number of elements in an array

9

In [12]:
np.where(arr1>0) # It will give you the number of indices/indexes where data is greater than zero

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [13]:
np.extract(arr1>0, arr1) # It's going to extract the data where elemnts are greater than zero

array([56, 21, 56, 32, 67, 21, 67, 34, 89])

In [14]:
# Numpy - Byte Swapping
arr1

array([ 0, 56, 21, 56, 32, 67, 21, 67, 34, 89])

In [15]:
arr1.byteswap() # For every data it will give you the byte representation

array([                  0, 4035225266123964416, 1513209474796486656,
       4035225266123964416, 2305843009213693952, 4827858800541171712,
       1513209474796486656, 4827858800541171712, 2449958197289549824,
       6413125869375586304])

In [16]:
arr1.byteswap(True)

array([                  0, 4035225266123964416, 1513209474796486656,
       4035225266123964416, 2305843009213693952, 4827858800541171712,
       1513209474796486656, 4827858800541171712, 2449958197289549824,
       6413125869375586304])

In [17]:
# Numpy - Copies and Views
arr1

array([                  0, 4035225266123964416, 1513209474796486656,
       4035225266123964416, 2305843009213693952, 4827858800541171712,
       1513209474796486656, 4827858800541171712, 2449958197289549824,
       6413125869375586304])

In [19]:
a = np.copy(arr1)
a

array([                  0, 4035225266123964416, 1513209474796486656,
       4035225266123964416, 2305843009213693952, 4827858800541171712,
       1513209474796486656, 4827858800541171712, 2449958197289549824,
       6413125869375586304])

In [21]:
a = np.copy(arr)
a

array([ 4,  2,  6,  8, 10,  9, 77, 56])

In [22]:
b = arr.view()
b

array([ 4,  2,  6,  8, 10,  9, 77, 56])

In [24]:
b[0] = 34
b

array([34,  2,  6,  8, 10,  9, 77, 56])

In [25]:
# Numpy - Matrix Library
import numpy.matlib as nm

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [40]:
# Numpy - Linear algebra
arr1 = np.random.randint([[2,3], [4,5]])
arr2 = np.random.randint([[5,3], [2,5]])

In [41]:
arr1


array([[1, 2],
       [1, 2]])

In [42]:
arr2

array([[4, 1],
       [1, 4]])

In [43]:
np.dot(arr1, arr2) # Dot product of arr1 and arr2

array([[6, 9],
       [6, 9]])

In [44]:
arr1@arr2 # Matrix multiplications

array([[6, 9],
       [6, 9]])